import type { Lang } from '../context/LanguageContext';

export const registrationContent = {
  en: {
  "pageTitle": "Driver Registration",
  "introText": "Please complete all fields below. This takes about 3–5 minutes.",
  "appPromo": "Prefer the app? Drivers can also register in FlexiShift:",
  "errorMsg": "Please fill in all required fields.",
  "regTypeLabel": "I am registering as",
  "regTypeDriverOnly": "Driver only",
  "regTypeDriverTruck": "Driver with truck",
  "regTypeTruckOnly": "Truck only (providing vehicle)",
  "referralLabel": "Referral code (optional)",
  "referralPlaceholder": "e.g. JOHN25",
  "fullNameLabel": "Full name",
  "dobLabel": "Date of birth",
  "loginSectionTitle": "Login details",
  "emailLabel": "Email address",
  "emailHint": "You'll use this to log in.",
  "emailPlaceholder": "you@example.com",
  "phoneLabel": "Phone number",
  "phonePlaceholder": "7012 345678",
  "countryCodeLabel": "Country code",
  "countryCodeSearch": "Search country or code",
  "countryCodeNoResults": "No matching countries",
  "passwordLabel": "Password",
  "passwordHint": "At least 8 characters, including a letter and a number.",
  "confirmPasswordLabel": "Confirm password",
  "pwMismatch": "Passwords do not match.",
  "pwShow": "Show",
  "pwHide": "Hide",
  "licenceLabel": "Licence documents",
  "licenceDropText": "Tap to upload or take a photo",
  "licenceHint": "Front & back of your driving licence (photo or PDF).",
  "pointsLabel": "Penalty points on licence",
  "convictionLabel": "Any criminal convictions?",
  "yes": "Yes",
  "no": "No",
  "tradeLabel": "Trade number (F-skatt, sole trader, etc.)",
  "tradePlaceholder": "F-skatt, sole trader, etc.",
  "tradeHint": "e.g. F-skatt number, sole trader ID, company registration.",
  "commentsLabel": "Additional comments",
  "commentsPlaceholder": "Optional",
  "vehicleSectionTitle": "Vehicle details",
  "truckWord": "Truck",
  "vehicleTypeLabel": "Vehicle type",
  "vehicleTypeSelectPlaceholder": "Select…",
  "vtBoxTruck": "Box truck",
  "vtCurtainside": "Curtainside",
  "vtFlatbed": "Flatbed",
  "vtTipper": "Tipper",
  "vtRefrigerated": "Refrigerated",
  "vtTanker": "Tanker",
  "vtCarTransporter": "Car transporter",
  "vtOther": "Other",
  "vehicleTypeOtherPlaceholder": "Please specify",
  "vehCapacityLabel": "Vehicle capacity",
  "vehCapacityPlaceholder": "e.g. 3000",
  "unitLitres": "litres",
  "compartmentsLabel": "Number of compartments",
  "compartmentsHint": "Capacity per compartment.",
  "compartmentWord": "Compartment",
  "vehRegNumberLabel": "Vehicle registration number (licence plate)",
  "vehRegNumberPlaceholder": "e.g. ABC 123",
  "vehicleDocsLabel": "Vehicle documents",
  "vehicleDocsHint": "Registration certificate & insurance document.",
  "advisoriesLabel": "Does the vehicle have any advisories?",
  "advisoryDetailsPlaceholder": "Please give details",
  "insuranceLabel": "Insurance confirmation",
  "driverInsuredText": "I confirm the driver holds valid insurance",
  "vehicleInsuredText": "I confirm the vehicle holds valid insurance",
  "consentSectionTitle": "Consent",
  "acceptTermsPrefix": "I have read and accept the",
  "termsLinkText": "Terms and Conditions",
  "acceptPrivacyPrefix": "I have read and accept the",
  "privacyLinkText": "Privacy Policy",
  "marketingText": "I'd like to receive occasional updates and offers by email or SMS (optional)",
  "submitBtn": "Submit registration",
  "submitting": "Submitting…",
  "submitError": "Something went wrong sending your registration. Please check your connection and try again.",
  "successTitle": "Registration received",
  "successBody1": "Thank you — we've received your details and will be in touch shortly.",
  "successBody2": "You can now close this window.",
  "footnoteText": "Your data is processed in accordance with our Privacy Policy.",
  "infoTitle": "Info",
  "tooltip": {
    "regType": "Choose whether you're registering as a driver only, a driver who also has a truck, or as someone providing a truck without driving it yourself.",
    "referral": "If someone referred you to FlexiShift, enter their referral code here.",
    "fullName": "Enter your full legal name exactly as it appears on your driving licence.",
    "dob": "Enter your date of birth. You must be at least 18 years old to register.",
    "email": "This is the email address you'll use to log in and receive updates about your application.",
    "phone": "Enter your local phone number without the country code. We'll use this number to contact you about jobs and to verify your account.",
    "countryCode": "Select the country calling code for your phone number. You can search by country name or code.",
    "password": "Choose a password with at least 8 characters, including a letter and a number.",
    "confirmPassword": "Re-enter the same password to make sure it was typed correctly.",
    "licenceDocs": "Upload clear photos or a PDF of the front and back of your driving licence.",
    "points": "Enter how many penalty points are currently on your licence. Enter 0 if you have none.",
    "conviction": "Let us know if you have any criminal convictions. This does not automatically disqualify you — each case is reviewed individually.",
    "tradeNumber": "If you're self-employed, enter your F-skatt number or equivalent trade or company registration number.",
    "comments": "Add anything else you think we should know about your application.",
    "vehicleType": "Select the body type of the truck, for example box truck, flatbed or tipper.",
    "vehCapacity": "Enter the maximum load capacity of this truck and choose the correct unit (kg, m³ or litres).",
    "vehCompartments": "Enter how many separate load compartments this truck has, then enter the capacity of each one.",
    "vehRegNumber": "Enter the vehicle's official registration number (licence plate).",
    "vehicleDocs": "Upload the vehicle's registration certificate and insurance document.",
    "advisories": "Tell us about any outstanding advisories or defects noted at the vehicle's last inspection, if any.",
    "insurance": "Confirm that both the driver and the vehicle currently hold valid insurance."
  },
  "backHome": "Back to home"
},
  no: {
  "pageTitle": "Sjåførregistrering",
  "introText": "Vennligst fyll ut alle feltene nedenfor. Dette tar cirka 3–5 minutter.",
  "appPromo": "Foretrekker du appen? Sjåfører kan også registrere seg i FlexiShift:",
  "errorMsg": "Vennligst fyll ut alle obligatoriske felt.",
  "regTypeLabel": "Jeg registrerer meg som",
  "regTypeDriverOnly": "Kun sjåfør",
  "regTypeDriverTruck": "Sjåfør med lastebil",
  "regTypeTruckOnly": "Kun lastebil (tilbyr kjøretøy)",
  "referralLabel": "Henvisningskode (valgfritt)",
  "referralPlaceholder": "f.eks. JOHN25",
  "fullNameLabel": "Fullt navn",
  "dobLabel": "Fødselsdato",
  "loginSectionTitle": "Innloggingsdetaljer",
  "emailLabel": "E-postadresse",
  "emailHint": "Du bruker denne for å logge inn.",
  "emailPlaceholder": "du@eksempel.com",
  "phoneLabel": "Telefonnummer",
  "phonePlaceholder": "900 00 000",
  "countryCodeLabel": "Landskode",
  "countryCodeSearch": "Søk land eller kode",
  "countryCodeNoResults": "Ingen treff",
  "passwordLabel": "Passord",
  "passwordHint": "Minst 8 tegn, inkludert en bokstav og et tall.",
  "confirmPasswordLabel": "Bekreft passord",
  "pwMismatch": "Passordene stemmer ikke overens.",
  "pwShow": "Vis",
  "pwHide": "Skjul",
  "licenceLabel": "Førerkortdokumenter",
  "licenceDropText": "Trykk for å laste opp eller ta et bilde",
  "licenceHint": "Fram- og bakside av førerkortet (bilde eller PDF).",
  "pointsLabel": "Prikker på førerkortet",
  "convictionLabel": "Har du noen straffedommer?",
  "yes": "Ja",
  "no": "Nei",
  "tradeLabel": "Org.nr. / F-skatt (enkeltpersonforetak e.l.)",
  "tradePlaceholder": "Org.nr., enkeltpersonforetak, e.l.",
  "tradeHint": "F.eks. organisasjonsnummer eller enkeltpersonforetak-ID.",
  "commentsLabel": "Andre kommentarer",
  "commentsPlaceholder": "Valgfritt",
  "vehicleSectionTitle": "Kjøretøydetaljer",
  "truckWord": "Lastebil",
  "vehicleTypeLabel": "Kjøretøytype",
  "vehicleTypeSelectPlaceholder": "Velg…",
  "vtBoxTruck": "Kassebil",
  "vtCurtainside": "Skyvepresenning",
  "vtFlatbed": "Planbil",
  "vtTipper": "Tippbil",
  "vtRefrigerated": "Kjølebil",
  "vtTanker": "Tankbil",
  "vtCarTransporter": "Biltransport",
  "vtOther": "Annet",
  "vehicleTypeOtherPlaceholder": "Vennligst spesifiser",
  "vehCapacityLabel": "Kjøretøyets kapasitet",
  "vehCapacityPlaceholder": "f.eks. 3000",
  "unitLitres": "liter",
  "compartmentsLabel": "Antall rom",
  "compartmentsHint": "Kapasitet per rom.",
  "compartmentWord": "Rom",
  "vehRegNumberLabel": "Kjøretøyets registreringsnummer",
  "vehRegNumberPlaceholder": "f.eks. AB 12345",
  "vehicleDocsLabel": "Kjøretøydokumenter",
  "vehicleDocsHint": "Vognkort og forsikringsbevis.",
  "advisoriesLabel": "Har kjøretøyet noen anmerkninger?",
  "advisoryDetailsPlaceholder": "Vennligst gi detaljer",
  "insuranceLabel": "Forsikringsbekreftelse",
  "driverInsuredText": "Jeg bekrefter at sjåføren har gyldig forsikring",
  "vehicleInsuredText": "Jeg bekrefter at kjøretøyet har gyldig forsikring",
  "consentSectionTitle": "Samtykke",
  "acceptTermsPrefix": "Jeg har lest og godtar",
  "termsLinkText": "vilkårene",
  "acceptPrivacyPrefix": "Jeg har lest og godtar",
  "privacyLinkText": "personvernerklæringen",
  "marketingText": "Jeg ønsker å motta oppdateringer og tilbud på e-post eller SMS (valgfritt)",
  "submitBtn": "Send inn registrering",
  "submitting": "Sender inn…",
  "submitError": "Noe gikk galt under innsending. Sjekk internettforbindelsen din og prøv igjen.",
  "successTitle": "Registrering mottatt",
  "successBody1": "Takk – vi har mottatt opplysningene dine og tar kontakt snart.",
  "successBody2": "Du kan nå lukke dette vinduet.",
  "footnoteText": "Dine opplysninger behandles i samsvar med vår personvernerklæring.",
  "infoTitle": "Info",
  "tooltip": {
    "regType": "Velg om du registrerer deg som kun sjåfør, som sjåfør med egen lastebil, eller som noen som stiller med kjøretøy uten selv å kjøre.",
    "referral": "Hvis noen har henvist deg til FlexiShift, skriv inn henvisningskoden deres her.",
    "fullName": "Skriv inn ditt fulle juridiske navn slik det står på førerkortet.",
    "dob": "Skriv inn fødselsdatoen din. Du må være minst 18 år for å registrere deg.",
    "email": "Dette er e-postadressen du bruker for å logge inn og motta oppdateringer om søknaden din.",
    "phone": "Skriv inn det lokale telefonnummeret uten landskode. Vi bruker dette nummeret til å kontakte deg om oppdrag og for å bekrefte kontoen din.",
    "countryCode": "Velg landskoden for telefonnummeret ditt. Du kan søke etter landnavn eller kode.",
    "password": "Velg et passord på minst 8 tegn, inkludert en bokstav og et tall.",
    "confirmPassword": "Skriv inn samme passord på nytt for å bekrefte at det er riktig.",
    "licenceDocs": "Last opp tydelige bilder eller en PDF av fram- og baksiden av førerkortet ditt.",
    "points": "Skriv inn hvor mange prikker du har på førerkortet. Skriv 0 hvis du ikke har noen.",
    "conviction": "Fortell oss om du har noen straffedommer. Dette diskvalifiserer deg ikke automatisk – hver sak vurderes individuelt.",
    "tradeNumber": "Hvis du er selvstendig næringsdrivende, skriv inn organisasjonsnummeret eller tilsvarende registreringsnummer.",
    "comments": "Legg til alt annet du synes vi bør vite om søknaden din.",
    "vehicleType": "Velg karosseritypen på lastebilen, for eksempel kassebil, planbil eller tippbil.",
    "vehCapacity": "Skriv inn maksimal lastekapasitet for denne lastebilen og velg riktig enhet (kg, m³ eller liter).",
    "vehCompartments": "Skriv inn hvor mange separate lasterom denne lastebilen har, og deretter kapasiteten til hvert av dem.",
    "vehRegNumber": "Skriv inn kjøretøyets offisielle registreringsnummer.",
    "vehicleDocs": "Last opp kjøretøyets vognkort og forsikringsbevis.",
    "advisories": "Fortell oss om eventuelle gjenstående anmerkninger eller mangler fra siste kontroll av kjøretøyet.",
    "insurance": "Bekreft at både sjåføren og kjøretøyet har gyldig forsikring."
  },
  "backHome": "Tilbake til hjem"
},
  sv: {
  "pageTitle": "Förarregistrering",
  "introText": "Fyll i samtliga fält nedan. Det tar cirka 3–5 minuter.",
  "appPromo": "Föredrar du appen? Förare kan också registrera sig i FlexiShift:",
  "errorMsg": "Vänligen fyll i alla obligatoriska fält.",
  "regTypeLabel": "Jag registrerar mig som",
  "regTypeDriverOnly": "Endast förare",
  "regTypeDriverTruck": "Förare med lastbil",
  "regTypeTruckOnly": "Endast lastbil (tillhandahåller fordon)",
  "referralLabel": "Rekommendationskod (valfritt)",
  "referralPlaceholder": "t.ex. JOHN25",
  "fullNameLabel": "Fullständigt namn",
  "dobLabel": "Födelsedatum",
  "loginSectionTitle": "Inloggningsuppgifter",
  "emailLabel": "E-postadress",
  "emailHint": "Du använder denna för att logga in.",
  "emailPlaceholder": "du@exempel.com",
  "phoneLabel": "Telefonnummer",
  "phonePlaceholder": "70 123 45 67",
  "countryCodeLabel": "Landskod",
  "countryCodeSearch": "Sök land eller kod",
  "countryCodeNoResults": "Inga träffar",
  "passwordLabel": "Lösenord",
  "passwordHint": "Minst 8 tecken, inklusive en bokstav och en siffra.",
  "confirmPasswordLabel": "Bekräfta lösenord",
  "pwMismatch": "Lösenorden matchar inte.",
  "pwShow": "Visa",
  "pwHide": "Dölj",
  "licenceLabel": "Körkortsdokument",
  "licenceDropText": "Tryck för att ladda upp eller ta ett foto",
  "licenceHint": "Fram- och baksida av ditt körkort (foto eller PDF).",
  "pointsLabel": "Antal prickar på körkortet",
  "convictionLabel": "Har du några brottmålsdomar?",
  "yes": "Ja",
  "no": "Nej",
  "tradeLabel": "F-skattenummer (enskild firma m.m.)",
  "tradePlaceholder": "F-skatt, enskild firma, etc.",
  "tradeHint": "T.ex. F-skattenummer, enskild firma, organisationsnummer.",
  "commentsLabel": "Övriga kommentarer",
  "commentsPlaceholder": "Valfritt",
  "vehicleSectionTitle": "Fordonsuppgifter",
  "truckWord": "Lastbil",
  "vehicleTypeLabel": "Fordonstyp",
  "vehicleTypeSelectPlaceholder": "Välj…",
  "vtBoxTruck": "Skåpbil",
  "vtCurtainside": "Skjutpresenning",
  "vtFlatbed": "Flak",
  "vtTipper": "Tippbil",
  "vtRefrigerated": "Kylbil",
  "vtTanker": "Tankbil",
  "vtCarTransporter": "Biltransport",
  "vtOther": "Annat",
  "vehicleTypeOtherPlaceholder": "Vänligen specificera",
  "vehCapacityLabel": "Fordonets kapacitet",
  "vehCapacityPlaceholder": "t.ex. 3000",
  "unitLitres": "liter",
  "compartmentsLabel": "Antal fack",
  "compartmentsHint": "Kapacitet per fack.",
  "compartmentWord": "Fack",
  "vehRegNumberLabel": "Fordonets registreringsnummer",
  "vehRegNumberPlaceholder": "t.ex. ABC 123",
  "vehicleDocsLabel": "Fordonsdokument",
  "vehicleDocsHint": "Registreringsbevis och försäkringsbrev.",
  "advisoriesLabel": "Har fordonet några anmärkningar?",
  "advisoryDetailsPlaceholder": "Vänligen ange detaljer",
  "insuranceLabel": "Försäkringsbekräftelse",
  "driverInsuredText": "Jag bekräftar att föraren har giltig försäkring",
  "vehicleInsuredText": "Jag bekräftar att fordonet har giltig försäkring",
  "consentSectionTitle": "Samtycke",
  "acceptTermsPrefix": "Jag har läst och godkänner",
  "termsLinkText": "användarvillkoren",
  "acceptPrivacyPrefix": "Jag har läst och godkänner",
  "privacyLinkText": "integritetspolicyn",
  "marketingText": "Jag vill gärna få uppdateringar och erbjudanden via e-post eller SMS (valfritt)",
  "submitBtn": "Skicka registrering",
  "submitting": "Skickar…",
  "submitError": "Något gick fel när registreringen skickades. Kontrollera din internetanslutning och försök igen.",
  "successTitle": "Registrering mottagen",
  "successBody1": "Tack – vi har tagit emot dina uppgifter och återkommer inom kort.",
  "successBody2": "Du kan nu stänga det här fönstret.",
  "footnoteText": "Dina uppgifter behandlas i enlighet med vår integritetspolicy.",
  "infoTitle": "Info",
  "tooltip": {
    "regType": "Välj om du registrerar dig som endast förare, som förare med egen lastbil, eller som någon som tillhandahåller ett fordon utan att själv köra.",
    "referral": "Om någon har rekommenderat dig till FlexiShift, ange deras rekommendationskod här.",
    "fullName": "Ange ditt fullständiga juridiska namn exakt som det står på ditt körkort.",
    "dob": "Ange ditt födelsedatum. Du måste vara minst 18 år för att registrera dig.",
    "email": "Det här är den e-postadress du använder för att logga in och få uppdateringar om din ansökan.",
    "phone": "Ange ditt lokala telefonnummer utan landskod. Vi använder detta nummer för att kontakta dig om uppdrag och för att verifiera ditt konto.",
    "countryCode": "Välj landskoden för ditt telefonnummer. Du kan söka på landsnamn eller kod.",
    "password": "Välj ett lösenord med minst 8 tecken, inklusive en bokstav och en siffra.",
    "confirmPassword": "Ange samma lösenord igen för att bekräfta att det stämmer.",
    "licenceDocs": "Ladda upp tydliga foton eller en PDF av fram- och baksidan av ditt körkort.",
    "points": "Ange hur många prickar du har på ditt körkort. Ange 0 om du inte har några.",
    "conviction": "Berätta om du har några brottmålsdomar. Detta diskvalificerar dig inte automatiskt – varje fall bedöms individuellt.",
    "tradeNumber": "Om du är egenföretagare, ange ditt F-skattenummer eller motsvarande registreringsnummer.",
    "comments": "Lägg till annat du tycker att vi bör känna till om din ansökan.",
    "vehicleType": "Välj lastbilens karosstyp, t.ex. skåpbil, flak eller tippbil.",
    "vehCapacity": "Ange fordonets maximala lastkapacitet och välj rätt enhet (kg, m³ eller liter).",
    "vehCompartments": "Ange hur många separata lastfack denna lastbil har, och ange sedan kapaciteten för varje fack.",
    "vehRegNumber": "Ange fordonets officiella registreringsnummer.",
    "vehicleDocs": "Ladda upp fordonets registreringsbevis och försäkringsbrev.",
    "advisories": "Berätta om eventuella kvarstående anmärkningar från fordonets senaste besiktning, om sådana finns.",
    "insurance": "Bekräfta att både föraren och fordonet har giltig försäkring."
  },
  "backHome": "Tillbaka till startsidan"
},
} as const;

export type RegistrationCopy = (typeof registrationContent)[Lang];
